name: "Check if compilable"

on: 
  push: 
    branches: main
  pull_request: 
    branches: main

jobq:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: action/setup-node@v2
        with:
          node-version: 18
      - run: npm cl
      - run: tsc -b